[phases.setup]
nixPkgs = ['php82', 'php82Extensions.intl', 'php82Extensions.zip', 'php82Extensions.bcmath', 'php82Extensions.ctype', 'php82Extensions.curl', 'php82Extensions.dom', 'php82Extensions.fileinfo', 'php82Extensions.filter', 'php82Extensions.gd', 'php82Extensions.mbstring', 'php82Extensions.openssl', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.session', 'php82Extensions.tokenizer', 'php82Extensions.xml']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
  'mkdir -p storage/framework/{sessions,views,cache,testing}',
  'mkdir -p storage/logs',
  'mkdir -p bootstrap/cache',
  'chmod -R 775 storage bootstrap/cache',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
